#!/bin/ash
#190508 sfs
# правки k0l0p0k 190510 поменял названия функций
# value - getcmd
# CP1 - copyAll
# INST32 - INST32OS
# INST - INSTg4d
# убрал установку всей оси из функции установки g4d
PART(){
#  запрос раздела GUI
d=/dev/sda
#dpm
dpart="$(ntf -l "`blkid |egrep -v "^/dev/sr|^/dev/loop"`" "На какой раздел скопировать grldr ?" "Файл загрузчика должен находиться на несъемном носителе" |awk -F: '{print $1}' |sed 's/dev/mnt/')"
[ "$dpart" ] ||PART
echo $dpart 
}

CP(){
#копирование GUI 
dpart="`echo "$dpart" |sed 's/dev/mnt/'`"
#echo "$d-$dp-$dpart" ;exit
mount-all `basename $dpart`

if [ -f "$dpart/$1" ] ;then
    ntf -q "$dpart/$1 существует" "Заменить?" && mv "$dpart/$1" "$dpart/$1.`date "+%y%m%d%H%M%S"`" || continue #return ?
fi
cp /usr/lib/grub4dos/"$1" "$dpart"
if [ -f "$dpart/$1" ] ;then
    ntf -i "Установка $dpart/$1 завершена успешно" &
else  ntf -a "Установка $dpart/$1 не произведена" && exit
fi
}
#dp=/dev/sde1 ;CP grldr ;exit
#value
getcmd() { egrep -o "(^| )$1=[^ ]+" /proc/cmdline | cut -d= -f2; } #sfs запрос параметров, переданных загрузчиком ядру
Installpra(){
[ "`getcmd root`" ] && install-pra || install-lf
}
#CP1()
copyAll(){
#	echo dpart="$dpart"
     CP menu.lst ; CP grldr ; CP rus_bold.lz
     Installpra "$dpart" ; exit
}
ERR() { [ ! "$d" ] && ntf -e "Ничего не выбрано" && exit ; }

INST32OS(){
# перезаписываем MBR копируем файлы g4d, ставим ось
 e="`/usr/lib/grub4dos/weesetup "$u" -b -s /usr/lib/grub4dos/weesetup.cfg --device="$d" 2>&1`"
     mount-all
 if [ "$?" = "0" ] ;then
     ntf -i "Установка MBR завершена успешно" &
     copyAll
 else  
    if [ "$e" = "wee already installed, use -u option!" ] ;then
	if ntf -q "MBR wee уже установлен\n" "Переустановить?" ;then
	    u="-u" && INSTg4d
	else copyAll
	fi
    else 
	echo e="$e"
	[ "$e" ] && ntf -a "Установка MBR не произведена\n" "$e" && exit || copyAll #??
    fi
 fi
}

DB(){
# поиск загрузочного	
dboot="`fdisk -l |awk '/^\/dev\/.*\*/ {print $1}'`"
#dboot="`fdisk -l |awk '/^\/dev\/.*/ {print $1}'`"
[ ! "$dboot" ] && ntf -a "Ни на oдном из разделов подключенных носителей не обнаружено установленного флага 'boot'" "Для установки флага используте gparted или cfdisk" && exit 1
for i in $dboot ;do
    db2="$db2
`blkid |egrep '^'$i''`"
done
}
# INST()
INSTg4d(){
#for i in `ls -1 /dev/[hs]d[a-z]` ;do
#for i in `ls -1 /dev/[hs][dr][a-z]` ;do
m0="- <b>Руководство</b> по grub4dos"
#d="$(ntf -l "$m0|`ls /dev/[hs]d[a-z]`" "Выберите устройство для установки grub4dos\n" "Перед установкой, про выбранное устройство будет выведена более полная информация")"
#d="$(ntf -l "$m0|`probedisk |tr "|" " "`" "Выберите устройство для установки grub4dos\n" "Перед установкой, про выбранное устройство будет выведена более полная информация")"
DB #
d="$(ntf -l "$m0|`blkid |egrep -v "^/dev/sr|^/dev/loop"`" "Выберите раздел для установки grub4dos\n" "Перед установкой, про выбранное устройство будет выведена более полная информация")"
#d="$(ntf -l "$m0|`echo "$db2" |sed '/^$/d'`" "Выберите раздел для установки grub4dos\n" "Перед установкой, про выбранное устройство будет выведена более полная информация")"
dpart="`echo $d| awk -F: '{print $1}'`"
#     echo d="$d" ;exit
#     dp="`echo "$d" |awk -F"/" '{print "/"$2"/"$3"1"}'`"
#dpart="`echo "$dp" |sed 's/dev/mnt/'`"
LANG=en_US.UTF-8 fdisk -l $dpart |egrep "^Disklabel type" |grep gpt && ntf -a "Grub4Dos не устанавливается на GPT." "Используйте grub2" && exit 1

if [ "$dpart" = "$m0" ] ;then
    defaultbrowser "http://greenflash.su/Grub4Dos/Grub4dos.htm" & 
    INSTg4d # 
fi
d="`echo $dpart |tr -d [0-9]`"
ERR
[ "`fdisk -l "$d" |egrep ' GPT$'`" ] && ntf -a "Установка на GPT не поддерживается" "`fdisk -l "$d"`" && exit
ntf -q "Вы уверены, что хотите установить grub4dos на\n$d ?
<b>Внимание!</b> Необдуманные действия могут привести к тому, что все системы c $d перестанут загружаться" "</i><small>`fdisk -l $d |egrep -v 'Units:| size '`</small><i>" || return
#cp -f /usr/lib/grub4dos/grldr.mbr /tmp/wee.mbr &&
#dd if=$d bs=1 skip=439 count=72 2>/dev/null | dd of=/tmp/wee.mbr bs=1 seek=439 conv=notrunc &&
#dd if=/tmp/wee.mbr of=$d &&
sudo -u `sfsusr` wt "sudo /usr/lib/grub4dos/bootlace.com $d" # ??
# ?? помимо г4д устанавливается ВСЯ система ??
#copyAll &&
CP menu.lst ; CP grldr ; CP rus_bold.lz &&
ntf -w "grub4dos" "успешно установлен на $d" && exit || ntf -w "grub4dos" "ОШИБКА установки!!!"
}

########   MAIN  #####################################################################

m0="<big>Установка системы ( <b>grub4dos</b>  уже установлен )</big>"
m4="<big>Установка <b>grub4dos</b> в MBR</big>" # (на устройстве нет установленных систем)"
m1="<b>Windows</b> уже установлен"
#m2="<b>Windows XP</b> уже установлен"
m3="<b>grub2</b>  уже установлен (или установка)"
m5="Используется <b>UEFI</b>"

d="$(ntf -l "$m4|$m0|$m1|$m3|$m5" "Установка системы и загрузчика" "Если носитель не размечен - сделайте это с помощью gparted
Если загрузчик <b>установлен - пропустите</b> первый шаг
Оптимально устанавливать на Linux раздел (например ext4)")"
#echo "d=$d"
case $d in
    "$m1") defaultbrowser "http://wiki.puppyrus.org/puppyrus/grub#установка_на_компьютер_с_windows" & ;;
#    "$m2") defaultbrowser "http://wiki.puppyrus.org/setups/g4d-xp" & ;;
    "$m3") defaultbrowser "http://wiki.puppyrus.org/puppyrus/grub#установка_grub2" & ;;
    "$m5") defaultbrowser "http://wiki.puppyrus.org/puppyrus/grub#uefi" & ;;
    "$m0") 
	echo dpart="$dpart"
	Installpra #"$dpart"
XXX(){
    h=Справка
    [ "`uname -m`" = "x86_64" ] && f="|Full"
    y="`ntf -l "$h|Frugal$f" "Установка PRA" "Выберите вариант установки"`"
 case $y in
    $h)		defaultbrowser "http://wiki.puppyrus.org/setups/full-vs-frugal" ; ($0 &) ;exit ;;
    Frugal)	install-pra  "$dpart" ;;
    Full)	pra-full-inst ;;
    *)		exit ;;
 esac
}
	exit
	;;
    "$m4") INSTg4d ;;
    *) ERR ;;
esac
#$0
exit
